### ISSUE TITLE
Is there a way of seeing the firebase firestore structure for this app

### ISSUE THREAD

**Issue by kcibdev** [loydkim/chat_app_loyd#3]
Am trying to see how you structure to the database, is there a way i can see that cause i have the check the dart code and still haven't seen where you created it @loydkim

**Comment by loydkim** [comment]
I didn't update the project and when I finish it, I will make the chat app explain video soon. Thanks.

If your firebase rule didn't change it, you have to change it. cause the chat app didn't use authentication.
